# SPDX-License-Identifier: AGPL-3.0-or-later
## Dynamic
- type: latheRecipePack
  id: ShrapnelAmmo
  recipes:
      - MagazineRifleShrapnel
      - MagazinePistolShrapnel
      - MagazinePistolSubMachineGunShrapnel
      - MagazineMagnumShrapnel
      - MagazineLightRifleShrapnel
      - MagazineBoxPistolShrapnel
      - MagazineBoxMagnumShrapnel
      - MagazineBoxLightRifleShrapnel
      - MagazineBoxRifleShrapnel

- type: latheRecipePack
  id: ShrapnelAmmoSyndicate
  recipes:
      - MagazineCaselessRifleShrapnel
      - MagazineCaselessRifleIncendiary
      - MagazineCaselessRifleUranium
      - MagazineBoxCaselessRifleShrapnel
      - MagazineBoxCaselessRifleIncendiary
      - MagazineBoxCaselessRifleUranium
