- type: gameMapPool
  id: DefaultMapPool
  maps:
  - Atlas
  #- Amber TODO: goob amber
  - Bagel
  - Box
  - Cluster
  - Core
  - Fland
 # - Gate Goobstation - My name is Walter Hartwell White, I live at 2308 Negra alloya line albequrque new mexico.
  - Loop
  - Marathon
  - Meta
  - Oasis
  - Omega
  - Origin
  - Packed
  - Reach
# - Train # Goobstation - all my friends hate train
  - FlandHighPop
  - OasisHighPop
  # NOBODY LOVES BARRATRY
  #- Barratry # Goobstation - Re-add barratry
  - Kettle # Goobstation - Re-add kettle (before it was gemini!)
  - Submarine # goobstation - kill yourse
  - Lambda # Goobstation - literally someone forgot to add it???
  - Leonid # Goobstation - for goob by goob
  - Delta # Goobstation - ported from Corvax
# RESERVE
  - ReserveSillyIsland # Reserve, silly port
  - ReserveSaltern
  - ReserveOmega
  - ReserveCluster
